package blocks

import (
	"encoding/json"
	"math"
	"os"
	"testing"
)

// The Go HSMM must reproduce scripts/hmm-decode-proto.py's viterbi_hsmm
// EXACTLY. The +0.073 holdout result was measured with the Python
// implementation, so a port that merely comes close ships something that was
// never measured. Golden vectors are regenerated by
// scripts/gen-hsmm-parity.py; they include real per-second probabilities
// because synthetic inputs are smooth and never produce the near-ties where a
// wrong tie-break direction hides.
func TestHSMMParityWithReference(t *testing.T) {
	raw, err := os.ReadFile("testdata/hsmm_parity.json")
	if err != nil {
		t.Fatalf("golden vectors missing (run scripts/gen-hsmm-parity.py): %v", err)
	}
	var golden struct {
		Params struct {
			AdMu      float64 `json:"ad_mu"`
			AdSD      float64 `json:"ad_sd"`
			ShowMu    float64 `json:"show_mu"`
			ShowSD    float64 `json:"show_sd"`
			EmitW     float64 `json:"emit_w"`
			DurW      float64 `json:"dur_w"`
			MinBlockS float64 `json:"min_block_s"`
			MaxBlockS float64 `json:"max_block_s"`
		} `json:"params"`
		Cases []struct {
			Name   string       `json:"name"`
			P      []float64    `json:"p"`
			Blocks [][2]float64 `json:"blocks"`
		} `json:"cases"`
	}
	if err := json.Unmarshal(raw, &golden); err != nil {
		t.Fatalf("golden vectors unreadable: %v", err)
	}
	if len(golden.Cases) == 0 {
		t.Fatal("golden vectors empty")
	}
	o := HSMMOpts{
		AdMuS: golden.Params.AdMu, AdSD: golden.Params.AdSD,
		ShowMuS: golden.Params.ShowMu, ShowSD: golden.Params.ShowSD,
		EmitW: golden.Params.EmitW, DurW: golden.Params.DurW,
		MinBlockS: golden.Params.MinBlockS, MaxBlockS: golden.Params.MaxBlockS,
	}
	for _, c := range golden.Cases {
		got := FormHSMM(c.P, o)
		if len(got) != len(c.Blocks) {
			t.Errorf("%s: got %d blocks, reference has %d (%v vs %v)",
				c.Name, len(got), len(c.Blocks), got, c.Blocks)
			continue
		}
		for i, want := range c.Blocks {
			// Boundaries are whole seconds on both sides; anything above a
			// rounding epsilon is a real divergence, not float noise.
			if math.Abs(got[i].StartS-want[0]) > 1e-9 ||
				math.Abs(got[i].EndS-want[1]) > 1e-9 {
				t.Errorf("%s block %d: got [%.3f,%.3f), reference [%.3f,%.3f)",
					c.Name, i, got[i].StartS, got[i].EndS, want[0], want[1])
			}
		}
	}
}

// PerSecondMean must match the reference to_seconds(): non-overlapping
// windows of fps frames, trailing partial second dropped. An off-by-one here
// shifts every boundary by a second without failing anything loudly.
func TestPerSecondMean(t *testing.T) {
	x := make([]float64, 0, 130)
	for i := 0; i < 130; i++ {
		x = append(x, float64(i))
	}
	got := PerSecondMean(x, 25)
	if len(got) != 5 {
		t.Fatalf("got %d seconds, want 5 (130 frames at 25 fps, remainder dropped)", len(got))
	}
	for i, want := range []float64{12, 37, 62, 87, 112} {
		if math.Abs(got[i]-want) > 1e-9 {
			t.Errorf("second %d: got %.4f, want %.4f", i, got[i], want)
		}
	}
	if PerSecondMean(nil, 25) != nil {
		t.Error("nil input must give nil")
	}
	if PerSecondMean(x, 0) != nil {
		t.Error("fps 0 must give nil, not a divide-by-zero")
	}
	if PerSecondMean(x[:10], 25) != nil {
		t.Error("fewer frames than one second must give nil")
	}
}

// Guards against the decoder emitting anything a downstream consumer would
// choke on, independent of what the reference does.
func TestHSMMOutputWellFormed(t *testing.T) {
	p := make([]float64, 4000)
	for i := range p {
		switch {
		case i > 800 && i < 1100, i > 2400 && i < 2700:
			p[i] = 0.93
		default:
			p[i] = 0.04
		}
	}
	got := FormHSMM(p, HSMMOpts{})
	if len(got) == 0 {
		t.Fatal("two clear breaks produced no blocks")
	}
	prevEnd := -1.0
	for i, b := range got {
		if b.EndS <= b.StartS {
			t.Errorf("block %d is empty or inverted: %v", i, b)
		}
		if b.Duration() < 60 {
			t.Errorf("block %d is %.0fs, below the 60s minimum", i, b.Duration())
		}
		if b.StartS < prevEnd {
			t.Errorf("block %d starts at %.0f, before the previous end %.0f",
				i, b.StartS, prevEnd)
		}
		if b.EndS > float64(len(p)) {
			t.Errorf("block %d ends at %.0f, past the %d s recording",
				i, b.EndS, len(p))
		}
		prevEnd = b.EndS
	}
	if got := FormHSMM(nil, HSMMOpts{}); got != nil {
		t.Errorf("empty input must give nil, got %v", got)
	}
}

// AdBiasLP: negativ = ad-avers. Der Test baut einen Block mit eindeutigem
// Kern und ambivalenten Raendern (p≈0.5) — genau die Zone, um die es geht.
func TestHSMMAdBias(t *testing.T) {
	p := make([]float64, 600)
	for i := range p {
		p[i] = 0.02
	}
	for i := 200; i < 210; i++ { // ambivalenter Vorlauf (Trailer-Zone)
		p[i] = 0.55
	}
	for i := 210; i < 330; i++ { // eindeutiger Werbe-Kern
		p[i] = 0.97
	}
	for i := 330; i < 340; i++ { // ambivalenter Nachlauf
		p[i] = 0.55
	}
	ohne := FormHSMM(p, HSMMOpts{DurW: 15})
	avers := FormHSMM(p, HSMMOpts{DurW: 15, AdBiasLP: -0.4})
	if len(ohne) != 1 || len(avers) != 1 {
		t.Fatalf("Blockzahl: ohne=%d avers=%d, will je 1", len(ohne), len(avers))
	}
	// Der Kern muss ueberleben — Bias darf keine Bloecke fressen.
	if avers[0].EndS-avers[0].StartS < 100 {
		t.Fatalf("avers-Block zu kurz: %v", avers[0])
	}
	// Ad-avers: Start NICHT frueher, Ende NICHT spaeter; und mindestens
	// eine Kante rueckt messbar nach innen.
	if avers[0].StartS < ohne[0].StartS || avers[0].EndS > ohne[0].EndS {
		t.Errorf("Bias weitet den Block: ohne=%v avers=%v", ohne[0], avers[0])
	}
	if (avers[0].StartS-ohne[0].StartS)+(ohne[0].EndS-avers[0].EndS) < 5 {
		t.Errorf("Bias bewegt die Raender nicht: ohne=%v avers=%v",
			ohne[0], avers[0])
	}
	// Bias 0 == Referenz (Paritaet der Nullstellung).
	null := FormHSMM(p, HSMMOpts{DurW: 15, AdBiasLP: 0})
	if len(null) != 1 || null[0] != ohne[0] {
		t.Errorf("AdBiasLP=0 nicht byte-identisch: %v vs %v", null, ohne)
	}
}
